name: Build on push master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: avinakefin/build-kernel@master
      id: build
      env:
        NAME: Samsoe
      with:
        arch: arm64
        compiler: gcc/10
        defconfig: ginkgo_defconfig
        image: Image.gz-dtb
        dtbo: dtbo.img

    - name: Release build
      uses: appleboy/telegram-action@master
      with:
        to: -510134769
        token: 1702742721:AAFKZlzVymadj-x-ZUtYMM_yehmhxFluTIk
        message: Kernel is built!, took ${{ steps.build.outputs.elapsed_time }} seconds.
        document: ${{ steps.build.outputs.outfile }}
